---
- question: 'How would you disable SSH login as root, on Linux?'
  answer: |-
    - Edit `/etc/ssh/sshd_config`, change `PermitRootLogin` from yes to no.
    - Reload `sshd`
  mark: 3
  years:
    2018:
      - AGM
    2017:
      - AGM

- question: 'Why might you want to run SSH on a non-standard port?'
  answer: 'It would be harder to brute force a user login.'
  mark: 2
  years:
    2017:
      - AGM

- question: >-
    You have forgotten the `passwordsafe` password. How do you gain access?
  answer: Ask another admin, encrypt it with PGP if you have to.
  mark: 2
  years:
    2017:
      - AGM

- question: '`chmod -R 777 ./*` Why is this literally the worst thing ever?'
  answer: >-
    It's basically open season for all users, groups and others to have a go at
    your files.
  mark: 3
  years:
    2017:
      - AGM

- question: |-
    A user has launched a new website for another society. They type `ls -l` and
    the following is output;
    ```bash
    gobshite@azazel (~/public_html/) -> ls -l               [8:25]
    total 12K
    -rwxrwxrwx 1 gobshite member 116 2013-10-21 19:55 blah.php
    -rwxrwxrwx 1 gobshite member 50 2013-10-21 19:25 database.php
    -rwxrwxrwx 1 gobshite member 1593 2013-10-21 19:17 index.php
    ```
    How would a regular user go about exploiting this?
  answer: |-
    - All files are world writable this allows any user to edit the `php`
      allowing them to edit the code that is executed.
    - They could read the database password from the `database.php` file and
      steal any info
  mark: 3
  years:
    2017:
      - AGM

- question: >-
    Apache runs as the `www-data` user, yet users scripts run as themselves. How
    is this done?
  answer: |-
    Web content should not be owned by this user, or a compromised web server
    would be able to rewrite a web site. Data written out by web servers will
    be owned by `www-data`.
  mark: 3
  years:
    2018:
      - AGM
    2017:
      - AGM

- question: >-
    What is wrong with the following? `mysql -u root -h mysql.internal
    -p=ThisIsTheRootPassword redbrickdb`
  answer: >-
    You are passing the Root Password to the console in plain text. This can
    show up in logs, history, you name it.
  mark: 2
  years:
    2018:
      - AGM
    2017:
      - AGM

- question: >-
    You see a massive spike in traffic from a pile of Chinese IP addresses. What
    do you do?
  answer: >-
    Ban Chinese IP's via subnet with iptables rules. There's lots of chinese ip
    adress space  youll need a large subnet
  mark: 2
  years:
    2018:
      - AGM
    2017:
      - AGM

- question: |-
    Briefly explain the purpose of each of the following:
      - `/etc/shadow` and `/etc/group`
      - SELinux
      - `dm-crypt`
      - SSL
      - KPTI
  answer: |-
    - `/etc/shadow` and `/etc/group`
      - 1. This is a file that stores encrypted user passwords and additional
        information about the user.
      - 2. This is a file the defines the groups to which users belong.
    - SELinux
      - SELinux provides security for the user data's from system services.
    - `dm-crypt`
    - SSL
      - SSL certificates are used to create an encrypted link between a client
        and server
    - KPTI
  mark: 5
  years:
    2018:
      - AGM
    2017:
      - AGM

- question: >-
    A major Linux security vulnerability has been announced. How do you go about
    patching your machines with minimal downtime?
  answer: ""
  mark: 5
  years:
    2017:
      - AGM

- question: >-
    How would you view the currently enforced iptables rules on a system?
  answer: '`iptables -L`'
  years:
    2018:
      - AGM

- question: >-
    What are Spectre and Meltdown? Briefly explain how ONE of them could be
    exploited.
  answer: |-
    - Spectre and Meltdown are vulnerabilities in modern machines which leak
      passwords and other sensitive data.
    - Meltdown breaks the most fundamental isolation between user applications
      and the operating system. This attack allows a program to access the
      memory, and thus also the secrets, of other programs and the operating
      system.
  years:
    2018:
      - AGM

- question: >-
    What is fail2ban? How would you help a user who has fallen foul of fail2ban?
  answer: |-
    - fail2ban is a piece of software which protects against brute force attacks
    - `sudo fail2ban-client get $JAIL_NAME actionunban $IP_ADDRESS`
  years:
    2018:
      - AGM

- question: What is a CVE, and why should you care?
  answer: ''
  years:
    2018:
      - AGM

- question: Tell us something interesting you know about computer security.
  answer: ''
  years:
    2018:
      - AGM

- question: >-
    You left a terminal unlocked where you were logged into a Redbrick server as
    root. Someone has done something nefarious, and deleted the history files.
    How could you go about finding out what they did?
  answer: ''
  years:
    2018:
      - AGM

- question: >-
    Name 3 things you would do to secure a newly-installed Ubuntu 16.04 server.
  answer: |-
    - Disable Login as Root.
    - Set up SSH key login.
    - Set up fail2ban with a sshd jail.
  years:
    2018:
      - AGM

- question: >-
    What is the difference between ‘sudo’ and ‘su’?
  answer: >-
    Su switches your account to another user requiring the users loging when no
    args are passed it defaults to the root user. Sudo runs a single command
    with root privileges – it doesn't switch to the root user or require a
    separate root user password.
  years:
    2018:
      - AGM

- question: What is PAM? What do we use it in conjunction with?
  answer: ''
  years:
    2018:
      - AGM

- question: Why do Redbrick NOT use POP, FTP or Telnet?
  answer: because all of these are unencrypted
  years:
    2018:
      - AGM
